config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    validates :title, presence: true, length: {minimum: 6, maximum: 100}
    validates :description, presence: true, length: {minimum: 10, maximum: 300}
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, uniqueness: true
    validates :name, presence: true
    validates :name, length:{ minimum: 3, maximum: 25}
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    has_many :articles, dependent: :destroy
    validates :username, presence: true,
    length: {minimum: 3, maximum: 100},
    uniqueness: { case_sensitive: false }
EMAIL_REGEX =  /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i               
validates :email, presence: true,
    length: {minimum: 5, maximum: 100},
    format: {with: EMAIL_REGEX}
has_secure_password
end

app/controllers/CategoriesController.rb
class CategoriesController < ApplicationController
    
    def new

    end

    def create


    end

    def index

    end

    def show
        
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in? #zapięcie helpera do widoków, nie tylko controlera

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    def logged_in?
        !!current_user
    end
    def require_user
        if !logged_in?
            flash[:alert] = "Musisz być zalogowany."
            redirect_to login_path
        end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy ]
    before_action :require_user, except: [:show, :index]
    before_action :require_same_user, only: [:edit, :update, :destroy]


    def show
    end

    def index
      @articles = Article.paginate(page: params[:page], per_page: 3)
      
    end
  
    def new
      @article = Article.new
    end
  
    def create
      @article = Article.new(article_params)
      @article.user = current_user
      if @article.save
        flash[:notice] = "Article was created successfully."
        redirect_to @article
      else
        render "new", status: :unprocessable_entity
      end
    end

    def edit
    end

    def update
        if @article.update(article_params)
        flash[:notice] = "Artcile edited"
        redirect_to @article
        else
            render "edit", status: :unprocessable_entity
        end

    end

    def destroy
        @article.destroy
        redirect_to articles_path
    end

    private

    def set_article
        @article = Article.find(params[:id])
    end

    def article_params
        params.require(:article).permit(:title, :description)
    end
    
    def require_same_user
      if current_user != @article.user && !current_user.admin?
        flash[:alert] = "Możesz edytować tylko swoje posty."
        redirect_to @article
      end
    end
    
  end 

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        redirect_to articles_path if logged_in? #kliknięcie HOME zalogowanego użytkownika wsadzi do widoku artykułów a nie strony głównej
    end
    def about
        
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new

    end

    def create
     user = User.find_by(email: params[:session][:email])
     if user && user.authenticate(params[:session][:password])
        session[:user_id] = user.id
        flash[:notice] = "Log in correct"
        redirect_to user
  
        
     else
        flash.now[:alert] = "Log in incorrect"
        render 'new' , status: :unprocessable_entity
     end
    end

    def destroy
        session[:user_id] = nil
        flash[:notice] = "Logged out"
        redirect_to root_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:edit, :update, :show, :destroy ]
    before_action :require_user, except: [:show, :index, :new, :create]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def index
       @users = User.all 
    end

    def new
        @user = User.new
    end
    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            flash[:notice] ="Your account is created correct."
            redirect_to articles_path           
        else
            render 'new', status: :unprocessable_entity  
        end
    end
    def edit
    end
    def update
        if @user.update(user_params)
            flash[:notice] = "User edited"
            redirect_to user_path
            else
                render "edit", status: :unprocessable_entity
        end
    end

    def show
        @articles = @user.articles
    end
    
    def destroy
        @user.destroy
        session[:user_id] = nil if @user == current_user #zerujemy sesję - inaczje błąd będzie 
        flash[:notice] = "Twoje konto zostało usunięte"
        redirect_to articles_path
    end

    private

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

    def set_user
        @user = User.find(params[:id]) 
    end

    def require_same_user
        if current_user != @user && !current_user.admin?
          flash[:alert] = "Możesz edytować tylko swoje konto."
          redirect_to @user
        end
      end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def gravatar_for(user, options = { size: 80})
        email_address = user.email.downcase
        hash = Digest::MD5.hexdigest(email_address)
        size = options[:size]
        gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
        image_tag(gravatar_url, alt: user.username, class: "rounded-circle shadow mx-auto d-block")
      end



      
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<% @articles.each do |article| %>
<div>
<div class="container">
    <div class="card text-center shadow mb-5 bg-body rounded">
        <div class="card-header">
            <%= gravatar_for article.user, size: 50 %>
            <%= link_to article.user.username, user_path(article.user) %>
        </div>
        <div class="card-body">
            <h5 class="card-title"><%= article.title%></h5>
            <p class="card-text"><%= article.description%></p>
        <div class="btn-group" role="group" aria-label="Basic example">
            <%= button_to "Show", article_path(article), method: :get, class:"btn btn-outline-secondary d-inline" %>
            <%# wyświetlanie przycisków "edytuj" i "usuń" tylko przez użytkownika%>
            <% if logged_in? && article.user == current_user %>
                <%= button_to "Edit", edit_article_path(article), method: :get, class: "btn btn-outline-secondary d-inline" %>
                <%= button_to "Delete", article_path(article), method: :delete, class: "btn btn-outline-secondary d-inline" %>
            <% end %>

        </div>    
                

        </div>
        <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(article.created_at) %> ago, 
            edited <%= time_ago_in_words(article.updated_at) %> ago</small>
        </div>
    </div>
</div>
<% end %>

app/views/articles/_form.html.erb
  <%= render 'shared/errors', obj: @article %>
 
  <%= form_with(model: @article, local: true) do |f| %>
<div class="container shadow mb-5 bg-body rounded p-4 ">   
    <div class="mb-3">
      <%= f.label :title %><br/>
      <%= f.text_field :title, class: "w-50" %>
    </div>
    
    <div class="mb-3">
      <%= f.label :description %><br/>
      <%= f.text_area :description, class: "w-100" %>
    </div>
    <p>
      <%= f.submit %>
     
    </p>
</div>
  <% end %>
<div class="p-5 container-fluid">
<%= button_to "Cancel", articles_path, method: :get, class: "position-sticky start-50 translate-middle-x" %>
</div>

app/views/articles/edit.html.erb
<h1 class= "text-center p-4">Edit article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class= "text-center p-4">Article list</h1>
<div class="d-flex justify-content-center text-center digg_pagination p-4">
    <%= will_paginate @posts, :container => false %>
</div>
<%= render 'article' %>



<div class="p-5" ><%=button_to "New", new_article_path, method: :get, id: "add_btn" %></div><br>
</div>

app/views/articles/new.html.erb
<h1 class= "text-center p-4">New article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 class="text-center mt-4"><%= @article.title %></h2>

<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
          by <%= @article.user.username %>
        </div>
        <div class="card-body">
          <div class="card-text text-left"><%= simple_format(@article.description) %></div>
          <% if logged_in? && (@article.user == current_user || current_user.admin?) #admin będzie mógł kasować konta użytkowników %> 
            <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-info" %>
            <%= link_to "Delete", article_path(@article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
          <% end %>
        </div>
        <div class="card-footer text-muted">
          <small>Created <%= time_ago_in_words(@article.created_at) %> ago, 
          edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer mt-auto py-3 bg-dark">
    <div class="container">
        <span class="text-muted">
            <div class="position-absolurte">&COPY; 2022 |
                <a href='mailto:slimakkrzysztof1@gmail.com' id="sign">Ślim<div class="position-relative d-inline-block " id="shiftedLetter">@</div>
                    <div class="position-relative d-inline-block" id="letterK">.....k</div>
                </a>
            </div>
        </span>
    </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %> 
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark position-sticky top-0" style="z-index: 10">
  <div class="container-fluid">
    
    <%= button_to "alpha blog", root_path, class: "navbar-brand text-light nav-btn-0", id: "logo", method: :get %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= button_to "Article list", articles_path, class: "nav-link text-light nav-btn-0", method: :get %>
        </li>
        <li class="nav-item">
          <%= button_to "Bloggers", users_path, class:"nav-link text-light nav-btn-0", method: :get %>
        </li>
        <li class="nav-item">
          <%= button_to "About", about_path, class:"nav-link text-light nav-btn-0", method: :get %>
        </li>
         
        
         <% if logged_in? %>
         
          <%if current_user.admin? %>
            <li class="nav-item">
            <%= button_to "(admin) " + current_user.username, user_path(current_user), class:"nav-link text-light nav-btn-0", method: :get %></li>
         <%else%>
            <%= button_to current_user.username, user_path(current_user), class:"nav-link text-light nav-btn-0", method: :get %></li>
         <% end %>

            <li class="nav-item">
            <%= button_to 'Logout', logout_path, class:"nav-link text-light nav-btn-0", method: :delete %></li>

          <% else %>
          <li class="nav-item">
           <%= button_to 'Log in', login_path, class:"nav-link text-light nav-btn-0", method: :get %></li>
          <li class="nav-item">
           <%= button_to 'Sign up', signup_path, class:"nav-link text-light nav-btn-0", method: :get %></li>
          
        <% end %>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn btn-light" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "custom", "data-tubo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %> 
  </head>

  <body class="d-flex flex-column min-vh-100">
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/messages' %>
    
    <%= yield %>
    
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/_jumbotron.html.erb
<div class="container" id="home-container">
<div class="jumbo">
<div class="p-5 mb-4 mt-5 rounded-3">
      <div class="container-fluid py-5" >
        <h1 class="display-5 fw-bold text-center">ALPHA BLOG</h1>
        <p class="fs-4 text-center">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nihil voluptas perferendis quod repudiandae provident tempore voluptatem eaque nobis tempora pariatur neque minima laboriosam eveniet modi maiores, adipisci obcaecati nesciunt. Nemo.</p>
        <%= button_to "Sign up", signup_path, method: :get, class:"btn btn-primary mt-5 btn-lg position-relative top-50 start-50 translate-middle"  %>
      </div>
    </div>
  </div>
  </div>

app/views/pages/about.html.erb
<h1>About page</h1>

app/views/pages/home.html.erb
<%= render 'jumbotron'%>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h2>The following errors prevented the <%= obj.class.name.downcase %> from being saved</h2>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>


<%= form_with(model: @user, local: true) do |f| %>
  
  <div class ="p-3">
    <div class="mb-3">
      <%= f.label :username %>
      <%= f.text_field :username, type:"text", class:"form-control"%>  
    </div>
        <div class="mb-3">
      <%= f.label :email %>
      <%= f.email_field :email, type:"email", class:"form-control"%>  
    </div>
        <div class="mb-3">
      <%= f.label :password %>
      <%= f.password_field :password, type:"password", class:"form-control"%>  
    </div>  
    <%= f.submit(@user.new_record? ? 'Sign up' : 'Save changes', class: "btn btn-primary") %>
  </div>

<% end %>

<div class="mb-3 text-center">
      <%= link_to '[ Cancel and return ]', users_path , class: "text-info" %>
</div>

app/views/users/edit.html.erb
<h1 class= "text-center p-4">Edit user</h1>

<%= render 'form' %>
<%= button_to "Delete profile", user_path(current_user), class: "nav-btn-0 m-3 text-danger", method: :delete, form: { data: { turbo_confirm: "Are you sure?" } } %>

app/views/users/index.html.erb
<h1 class= "text-center p-4">Alpha Blogers</h1>

<% @users.each do |user| %>
<div>
<div class="container">
    <div class="card text-center shadow mb-5 bg-body rounded">
        <div class="card-header">
            <%= user.username %>
        </div>
        <div class="card-body">
        <%= gravatar_for user, size: 100 %>
            <h5 class="card-text"><%= user.email%></h5>
            <p class="card-text">Number of created articles: <%= user.articles.count%></p>
        <div class="btn-group" role="group" aria-label="Basic example">
            <%= button_to "Show", user_path(user), method: :get, class:"btn btn-outline-secondary d-inline" %>
            <% if logged_in? %>
                <% if user == current_user %>
                    <%= button_to "Edit", edit_user_path(user), method: :get, class: "btn btn-outline-secondary d-inline" %>
                <% end %>
                <%if current_user.admin? %>
                    <%= button_to "Delete (admin)", user_path(user), method: :delete, class: "btn btn-outline-danger d-inline", form: { data: { turbo_confirm: "Are you sure?" } } %>
                <% end %>
            <% end %>
        </div>    
                

        </div>
        <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(user.created_at) %> ago
        </div>
    </div>
</div>
<% end %>

app/views/users/new.html.erb
<h1 class= "text-center p-4">Create new user</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 class= "text-center p-4"><%= @user.username %> profile</h1>


<%= gravatar_for @user, size: 200 %>

<div class="container text-center p-3">
<% if logged_in? && @user == current_user %>
<%= button_to "Edit profile", edit_user_path, method: :get, class: "btn btn-outline-secondary d-inline" %>
<% end %>
</div>
<h3 class="text-center mt-4">Articles</h3>

<%= render 'articles/article' %>